Tuesday, August 24, 2021
10:07 AM
# This workflow will Rebuild Malaria Docs triggered when a push or pull_request event is triggered.

name: Rebuild Malaria Docs
on:
  push:
    paths:
      - '**.py'
      - '**/*docs/**'
      - '**/requirements.txt'
  
  pull_request:
    paths:
      - '**.py'
      - '**/*docs/**'
      - '**/requirements.txt'
   
jobs:
  emodpy-malaria-docs-rebuild:
runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
    
    # Environment Setup
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9 
          
    - name: Install emodpy-malaria requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
        echo -----------------------
    - name: Install the emodpy-malaria package
      run: |
        pip install -e . --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
    - name: Install documentation build requirements
      run: |
        pip install -r docs/requirements.txt --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
    - name: Build docs HTML --keep-going
      working-directory: 'docs'
      run: |
        make clean
        make html
    - name: DISABLED Build docs LINKCHECK --keep-going
      working-directory: 'docs'
      run: |
        echo make linkcheck
